# Generated by Django 4.1.7 on 2023-05-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("img_file", models.FileField(upload_to="img_file/%Y_%m_%d/")),
            ],
        ),
    ]
