# Generated by Django 4.1.7 on 2023-05-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0002_imagefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secfile",
            name="sec_file",
            field=models.FileField(upload_to="sec_file/%Y_%m_%d/"),
        ),
    ]
