# Generated by Django 4.1.7 on 2023-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0003_alter_secfile_sec_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CDS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DHT_humi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DHT_temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
