# Generated by Django 4.1.7 on 2023-05-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0004_cds_dht_humi_dht_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlCurtain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("control", models.BooleanField(default=False)),
            ],
        ),
    ]
