# Generated by Django 4.1.7 on 2023-05-24 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0009_standardhumidity_standardtemperature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlcurtain",
            name="alarm_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 24, 10, 30, 32, 540126, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
