# Generated by Django 4.1.7 on 2023-05-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0011_curtaintime_remove_controlcurtain_alarm_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalSmartControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_control", models.BooleanField(default=False)),
            ],
        ),
    ]
